# Generated by Django 4.0.3 on 2022-03-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('4', 'Expert'), ('1', 'Beginner'), ('0', 'Fundamental'), ('2', 'Intermediate'), ('3', 'Advanced')], max_length=20),
        ),
    ]
